<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Car;
use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{

    public function setState($idCar, $state){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "UPDATE AppBundle\Entity\Car car SET car.state=:state WHERE car.id=:id"
        )->setParameters(["state" => $state, "id" => $idCar])->execute();        
    }
}
