<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Car;
use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{



}
