<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{

    public function setState($idDriver, $state){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "UPDATE AppBundle\Entity\Driver d SET d.state=:state WHERE d.id=:id"
        )->setParameters(["state" => $state, "id" => $idDriver])->execute();        
    }

    public function getId($idUser){
        $em = $this->getEntityManager();
        $con = $em->getConnection();
        $sql = "SELECT d.id
        FROM driver d, user u
        WHERE d.user_id = u.id
        AND u.id = :id";
        $query = $con->prepare($sql);
        $query->bindValue("id",$idUser);
        $query->execute();
        $results = $query->fetchAll();
        return $results;        
    }

    



}
