<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{

    public function setState($idCar, $state){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "UPDATE AppBundle\Entity\Driver d SET d.state=:state WHERE d.id=:id"
        )->setParameters(["state" => $state, "id" => $idCar])->execute();        
    }


}
