<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function isTypeUser($table, $user_id)
    {

        
        
        $sql = "SELECT ".$table.".id FROM user, ". $table ." WHERE :user_id = ". $table .".user_id";
        $params = array(
            'user_id' => $user_id,
            'table' => $table
        );

        $results = $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();


        if ($results[0]["id"]){
            return true;
        }
        return false;
        // $em = $this->getEntityManager();
        // $connection = $em->getConnection();
        // $statement = $connection->prepare("SELECT company.id FROM user, company WHERE :user_id = company.user_id");
        // $statement->bindValue('user_id', $user_id);
        // $statement->execute();
        // $results = $statement->fetchAll();

        // return $results;
    }
    
}
