<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function isTypeUser($table, $companyId)
    {

        
        
        $sql = "SELECT ".$table.".id FROM company, ". $table ." WHERE :company_id = ". $table .".companys_id";
        $params = array(
            'company_id' => $companyId,
            'table' => $table
        );

        $results = $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();


        if ($results[0]["id"]){
            return true;
        }
        return false;
    }
    
}
