homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }


logout:
    path: /logout


register:
    path:      /register
    defaults:  { _controller: AppBundle:User:register }

ajax_register:
    path:      /register_ajax
    defaults:  { _controller: AppBundle:User:registerAjax }


# CAR ROUTING

new_car:
    path:   /car/new
    defaults:  { _controller: AppBundle:Car:new }


new_car:
    path:   /car/newAjax
    defaults:  { _controller: AppBundle:Car:newAjax }

show_car:
    path:   /carShow
    defaults:  { _controller: AppBundle:Company:showCars }

list_all_cars:
    path:   /listAllCars
    defaults:  { _controller: AppBundle:Company:listCars }

list_cars:
    path:   /listDivers/{state}
    defaults:  { _controller: AppBundle:Company:listCars }      

#DRIVER ROUTING

driver_register:
    path:   /register_driver
    defaults:   { _controller: AppBundle:Company:registerDriver }

show_drivers:
    path:   /driverShow
    defaults:  { _controller: AppBundle:Company:showDrivers }

list_all_drivers:
    path:   /listAllDrivers
    defaults:  { _controller: AppBundle:Company:listDrivers }

ajax_register_driver:
    path:   /ajax_register_driver
    defaults:   { _controller: AppBundle:Company:addDriver }

panel:
    path:      /panel
    defaults:  { _controller: AppBundle:User:panel }




