# Index routing
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

# Go to login page
login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }

# Go to login page
login_failure:
    path:      /loginFailure
    defaults:  { _controller: AppBundle:User:loginFailure }  

# Go to close session
logout:
    path: /logout

# Go to show form for register
register:
    path:      /register
    defaults:  { _controller: AppBundle:Company:register }

#Go to obtain data with register form
ajax_register:
    path:      /register_ajax
    defaults:  { _controller: AppBundle:Company:registerAjax }

register_user:
    path:   company/register_user
    defaults:  { _controller: AppBundle:Company:registerUser }

ajax_register_user:
    path:   company/register_user_ajax
    defaults:  { _controller: AppBundle:Company:registerUserAjax }    

# CAR ROUTING

register_car:
    path:   company/car/new
    defaults:  { _controller: AppBundle:Company:registerCar }


add_car:
    path:   company/car/addCar
    defaults:  { _controller: AppBundle:Company:addCar }

# Go to view for cars datatable 
show_car:
    path:   company/car/show
    defaults:  { _controller: AppBundle:Company:showCars }

edit_car:
    path: company/car/edit/{idCar}
    defaults:  { _controller: AppBundle:Car:edit }

edit_car_ajax:
    path: company/car/edit_ajax/
    defaults:  { _controller: AppBundle:Car:editAjax }

delete_car:
    path: company/car/delete/
    defaults:  { _controller: AppBundle:Car:delete }

# Obtain all cars with ajax
list_all_cars:
    path:   company/listAllCars
    defaults:  { _controller: AppBundle:Company:listCars }

# Obtain all cars filtering with state
list_cars:
    path:   company/listDivers/{state}
    defaults:  { _controller: AppBundle:Company:listCars }      


# Go to view for drivers datatable 
show_drivers:
    path:   company/driverShow
    defaults:  { _controller: AppBundle:Company:showDrivers }

# Obtain all drivers with ajax
list_all_drivers:
    path:   company/listAllDrivers
    defaults:  { _controller: AppBundle:Company:listDrivers }

# Show form view for register driver
driver_register:
    path:   company/register_driver
    defaults:   { _controller: AppBundle:Company:registerDriver }

# Register driver with ajax
ajax_register_driver:
    path:   company/ajax_register_driver
    defaults:   { _controller: AppBundle:Company:addDriver }

asign_car_driver:
    path:   company/asignCar
    defaults:   { _controller: AppBundle:Company:asignCar }

asign_car_to_driver:
    path: company/asignCarToDriver
    defaults:   { _controller: AppBundle:Company:asignCarToDriver}

edit_driver:
    path: driver/edit/{idDriver}
    defaults:  { _controller: AppBundle:Driver:edit }

edit_info_driver:
    path: driver/edit/{idDriver}
    defaults:  { _controller: AppBundle:Driver:edit }    

edit_driver_ajax:
    path: driver/edit_ajax/
    defaults:  { _controller: AppBundle:Driver:editAjax }

delete_driver:
    path: company/driver/delete/
    defaults:  { _controller: AppBundle:Driver:delete }    

# Show form view for register car
car_register:
    path:   company/register_car
    defaults:   { _controller: AppBundle:Company:registerCar }

# Register car with ajax
ajax_register_car:
    path:   company/ajax_register_car
    defaults:   { _controller: AppBundle:Company:addCar}

open_map:
    path: company/map
    defaults: { _controller: AppBundle:Company:openMap}

open_map_driver:
    path: driver/map
    defaults: { _controller: AppBundle:Driver:openMap}

change_state_driver_ajax:
    path: driver/changeStateAjax
    defaults: { _controller: AppBundle:Driver:setState}

change_state_driver:
    path: driver/changeState/{id}
    defaults: { _controller: AppBundle:Driver:showFormSetState}

unassign_car:
    path: driver/unassign/
    defaults: { _controller: AppBundle:Driver:unassignCar}    

#Show panel view
panel:
    path:      /panel
    defaults:  { _controller: AppBundle:User:panel }

show_edit_company:
    path:  /company/edit
    defaults:  { _controller: AppBundle:Company:showEditCompany }

edit_company:
    path:  /company/editAjax
    defaults:  { _controller: AppBundle:Company:editCompany }

email_confirmation:
    path:  /register/confirm
    defaults:  { _controller: AppBundle:Security:registerConfirmation }

send_email_confirmation:
    path:  /register/sendEmail
    defaults:  { _controller: AppBundle:Security:sendEmailConfirmation }

password_reset_create_token:
    path:  /password-reset
    defaults:  { _controller: AppBundle:Security:createTokenPassword }

password_reset_show_form:
    path:  /password-reset/restore
    defaults:  { _controller: AppBundle:Security:showFormRestorePassword }

password_reset_change:
    path:  /password-reset/change
    defaults:  { _controller: AppBundle:Security:changePassword }    

test_template:
    path:  /testTemplate
    defaults:  { _controller: AppBundle:Security:testTemplateEmail }



show_forget_password:
    path:  /password-reset/forgot
    defaults:  { _controller: AppBundle:Security:showForgetPassword } 

send_forget_password:
    path:  /sendForgetPassword
    defaults:  { _controller: AppBundle:Security:sendForgetPassword }

show_recovery_password:
    path:  /recoveryPassword
    defaults:  { _controller: AppBundle:Security:showRecoveryPassword }
