# Index routing
homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

# Go to login page
login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }

# Go to close session
logout:
    path: /logout

# Go to show form for register
register:
    path:      /register
    defaults:  { _controller: AppBundle:User:register }

#Go to obtain data with register form
ajax_register:
    path:      /register_ajax
    defaults:  { _controller: AppBundle:User:registerAjax }


# CAR ROUTING

new_car:
    path:   /car/new
    defaults:  { _controller: AppBundle:Car:new }


new_car:
    path:   /car/newAjax
    defaults:  { _controller: AppBundle:Car:newAjax }

# Go to view for cars datatable 
show_car:
    path:   /carShow
    defaults:  { _controller: AppBundle:Company:showCars }

# Obtain all cars with ajax
list_all_cars:
    path:   /listAllCars
    defaults:  { _controller: AppBundle:Company:listCars }

# Obtain all cars filtering with state
list_cars:
    path:   /listDivers/{state}
    defaults:  { _controller: AppBundle:Company:listCars }      


# Go to view for drivers datatable 
show_drivers:
    path:   /driverShow
    defaults:  { _controller: AppBundle:Company:showDrivers }

# Obtain all drivers with ajax
list_all_drivers:
    path:   /listAllDrivers
    defaults:  { _controller: AppBundle:Company:listDrivers }

# Show form view for register driver
driver_register:
    path:   /register_driver
    defaults:   { _controller: AppBundle:Company:registerDriver }

# Register driver with ajax
ajax_register_driver:
    path:   /ajax_register_driver
    defaults:   { _controller: AppBundle:Company:addDriver }

asign_car_driver:
    path:   /asignCar
    defaults:   { _controller: AppBundle:Company:asignCar }

# Show form view for register car
car_register:
    path:   /register_car
    defaults:   { _controller: AppBundle:Company:registerCar }

# Register car with ajax
ajax_register_car:
    path:   /ajax_register_car
    defaults:   { _controller: AppBundle:Company:addCar}

#Show panel view
panel:
    path:      /panel
    defaults:  { _controller: AppBundle:User:panel }




