homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }

register:
    path:      /register
    defaults:  { _controller: AppBundle:User:register }

list_cars:
    path:   /listAllCars
    defaults:  { _controller: AppBundle:Company:listCars }

list_cars:
    path:   /listCars/{state}
    defaults:  { _controller: AppBundle:Company:listCars }
list_cars:
    path:   /listAllDrivers
    defaults:  { _controller: AppBundle:Company:listCars }

list_cars:
    path:   /listDivers/{state}
    defaults:  { _controller: AppBundle:Company:listCars }      
