# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    car_service:
        class: AppBundle\Service\CarService
        arguments: [ "@doctrine.orm.entity_manager" ]
    app.user_service:
        class:     AppBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager"]
    app.company_service:
        class:     AppBundle\Service\CompanyService
        arguments: ["@doctrine.orm.entity_manager"] 
    app.driver_service:
        class:     AppBundle\Service\DriverService
        arguments: ["@doctrine.orm.entity_manager"]
             
    
